
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'execLETTERA LETTERB\n    exec : R\n    empty : \n    R : LETTERA LETTERA R LETTERB\n      | LETTERA R LETTERB R LETTERA\n      | LETTERB R LETTERA LETTERA\n      | empty\n    '
    
_lr_action_items = {'LETTERA':([0,3,4,5,6,8,10,11,12,13,14,15,],[3,6,3,-6,6,11,3,14,3,15,-5,-4,]),'LETTERB':([0,3,4,5,6,7,9,10,12,14,15,],[4,4,4,-6,4,10,12,4,4,-5,-4,]),'$end':([0,1,2,5,12,14,15,],[-2,0,-1,-6,-3,-5,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exec':([0,],[1,]),'R':([0,3,4,6,10,12,],[2,7,8,9,13,13,]),'empty':([0,3,4,6,10,12,],[5,5,5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exec","S'",1,None,None,None),
  ('exec -> R','exec',1,'p_exec','plytest.py',22),
  ('empty -> <empty>','empty',0,'p_empty','plytest.py',26),
  ('R -> LETTERA LETTERA R LETTERB','R',4,'p_R','plytest.py',31),
  ('R -> LETTERA R LETTERB R LETTERA','R',5,'p_R','plytest.py',32),
  ('R -> LETTERB R LETTERA LETTERA','R',4,'p_R','plytest.py',33),
  ('R -> empty','R',1,'p_R','plytest.py',34),
]
